# Site settings
title: teambunker
email: hoemoonee@gmail.com
author: teambunker
description: "teambunker."
baseurl: ""
url: "http://teambunker.github.io"

# Build settings
markdown: redcarpet
redcarpet:
    extensions: 
      - no_intra_emphasis
#      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap
      - highlight
      - quote
permalink: pretty
safe: true
highlighter: pygments
lsi: false
paginate: 10
