# Site settings
title: teambunker
email: hoemoonee@gmail.com
author: teambunker
description: "teambunker."
baseurl: ""
url: "http://teambunker.github.io"

# Build settings
markdown: kramdown
kramdown:
	input: GFM
permalink: pretty
paginate: 3
