# Site settings
title: teambunker
email: hoemoonee@gmail.com
author: teambunker
description: "teambunker."
baseurl: ""
url: "http://teambunker.gitub.io"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
